version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.4.0

workflows:
  version: 2

  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_REGION
          dockerfile: app/Dockerfile
          path: app
          repo: tsub-sandbox/app
          filters:
            branches:
              only:
                - master
