version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

    commands:
      - aws --version

  pre_build:
    commands:
      - |
        ECR_IMAGE_SOURCE_PATH="$CODEBUILD_SRC_DIR/imageDetail.json"
        cat $ECR_IMAGE_SOURCE_PATH | jq -r .
      - |
        IMAGE_URI=$(cat $ECR_IMAGE_SOURCE_PATH | jq -r '.ImageURI' | cut -d "@" -f 1)
        echo $IMAGE_URI

  build:
    commands:
      - printf '[{"name":"app","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json

artifacts:
    files: imagedefinitions.json
